AutomaApp/automa

- src/components/newtab/workflow/edit/EditTrigger.vue
Just a small spelling mistake 😊
Thanks,
> chore: fix spelling mistake

- src/assets/css/tailwind.css
- src/components/newtab/workflow/WorkflowDetailsCard.vue
inspired by https://kryogenix.org/code/browser/custom-drag-image.html
Origin: 
After:
> fix: drag square corners not transparent

- src/newtab/pages/workflows/[id].vue
> fix: Trigger missing time value handler

- src/locales/zh-TW/blocks.json
- src/locales/zh-TW/common.json
- src/utils/shared.js
update locales/blocks.js & common.js, my friend will update another 2 files, sorry about PR like this, we are newbie frontend developers, just want to experience more public project git-flow
> feat(locale): add zh-TW locale

- src/locales/en/newtab.json
- src/locales/en/popup.json
- src/locales/zh-TW/newtab.json
- src/locales/zh-TW/popup.json
Hello, Dear Kholid060
It's my fault to overwrite the origin json fiiles in dir en
now I fix it
thanks
> (fix):change dir of zh_TW json files,recover files in en

- src/background/workflow-engine/blocks-handler/handler-trigger.js
> fix: visit web trigger not working

- src/background/workflow-engine/blocks-handler/handler-conditions.js
Fixes error "Cannot read properties of undefined (reading 'replace')"
> Fix: conditions

- src/utils/shared.js
- src/utils/testConditions.js
Add RegEx comparison with the first value as a text and regex to the second value.
How to test:
0. Put a simple text in the first value, eg. "Hello, wOrLD!"
1. Input, "/world\!$/i" to the second value
2. The comparison should be true
> feat: add rgx comparison

- .eslintrc.js
- package.json
- src/components/newtab/workflow/WorkflowDetailsCard.vue
- src/content/index.js
- src/manifest.chrome.json
- src/manifest.firefox.json
- src/newtab/App.vue
- src/utils/workflowData.js
- yarn.lock
- Remove Vue Inspector Agnostic from package.json
- Collapsible description
- Auto install from URL (from file URL too) but only works on Chrome
> feat: collapsible description and auto install

- src/utils/referenceData/mustacheReplacer.js
- feature: add func replace
- add func toLowerCase and toUpperCase
> feature: add replace, toLowerCase, and toUpperCase functions

- src/utils/referenceData/mustacheReplacer.js
test playbook: http://runkit.com/mgilangjanuar/extractstrfunction
> fix: support single quote for string params

- webpack.config.js
Fix the i18n warning https://github.com/intlify/vue-i18n-next/issues/789#issuecomment-1164253341
> fix: fix vue-i18n warning

- src/newtab/router.js
> fix: fix Warning: No match found for location with path "/logs"

- src/locales/zh/blocks.json
> Update zh-cn blocks.json 

- src/components/content/selector/SelectorBlocks.vue
> fix: element selector blocks tab select border is blocked (#1079)

- src/locales/fr/blocks.json
update locales French - blocks.json to match v1.27.1
> update locales FR - blocks.json (=> 1.27.1)

- src/utils/message.js
> fix: MessageListener on Judgment is meaningless (#1132)

- jsconfig.json
- src/components/newtab/logs/LogsHistory.vue
- src/utils/dataExporter.js
- src/utils/getTranslateLog.js
- src/utils/shared.js
- src/workflowEngine/WorkflowEngine.js
- src/workflowEngine/blocksHandler/handlerLogData.js
1. Added jsconfig.json
2. Need to handle deep objects otherwise it will return :[object Object]
3. Fix the bug that "Get Log Data Block" can't get the latest logs, change it to get the latest logs from the current workflow state and convert it to text and json
> Fix the bug that "Get Log Data Block" can't get the latest logs, 

- src/background/BackgroundWorkflowUtils.js
Under v2 background running and creating a separate window should be the same #1155
> feat: Under v2 background running and creating a separate window should be the same

- src/newtab/pages/workflows/[id].vue
Add the required  `target`  parameter to the  `undoRedoCommand`  method.
> [Fix] resolved the issue of undo/redo not working

- src/sandbox/utils/handleConditionCode.js
fix [issue](https://github.com/AutomaApp/automa/issues/1363)
> Fix: handleConditionCode add check

- src/background/BackgroundUtils.js
> Fix: set default window size

- src/content/index.js
- src/workflowEngine/WorkflowWorker.js
> Fix(#1430): Concurrently execute

- src/assets/css/tailwind.css
This pull request addresses an issue with the display of Vietnamese text by modifying the font-family property. Previously, Vietnamese text might not have been rendered correctly due to the absence of a fallback font. This change adds a fallback font option to ensure proper display across various environments.
```diff
- font-family: 'Inter var' !important;
+ font-family: 'Inter var', sans-serif !important;
```
To ensure that the display of Vietnamese text is fixed, the following steps were taken:
This change has been tested and confirmed to resolve the issue with Vietnamese text display.
> Fix Vietnamese Text Display

- src/workflowEngine/index.js
feat: Add the globalData parameter to the workflowEventHandler method.
> feat: Add the globalData parameter to the workflowEventHandler method.
