src/content/services/recordWorkflow/recordEvents.js
Changes:
- Exclude the `aria-disabled` attribute to get selector when recording workflow.
Why:
- It's not important for a selector that identified by `aria-disabled` attr
- It's used for flagging the element whether it's disabled (https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-disabled)
=> enhancement: exclude aria-disabled to find selector when record workflow

src/content/elementSelector/generateElementsSelector.js, src/lib/findSelector.js
- delete the tagname in the element selector form, it's usually mismatched with the selected element
- update  to `data-testid` instead of using aria-label to get the high priority attr (https://www.educative.io/answers/what-is-the-data-testid-attribute-in-testing)
=> enhancement: element selector

utils/build-zip.js
```
$ node utils/build-zip.js
node:internal/fs/utils:345
throw err;
^
Error: ENOENT: no such file or directory, mkdir 'E:\webProject\automa\build-zip\1.24.3'
{
errno: -4058,
syscall: 'mkdir',
code: 'ENOENT',
}
```
=> Fix failure to create multi-level directories, e.g. (build-zip/version)

src/utils/FindElement.js
Add a custom "Sizzle" pseudo-class selector
"`:contains`": element content will be selected as long as it contains text
"`:equal`" : element content must be exactly the same as text to be selected
Example: `p.description:equal("cat")`
=> feat: Add a custom Sizzle pseudo-class selector :equal

src/utils/FindElement.js
Fix Sizzle's incorrect context in iframe
=> fix: Fix Sizzle incorrect context in iframe, passed as context of iframe

src/utils/handleFormElement.js
On sites that use jQuery and inputmask, inputmask will format the text and reset element.value when the keyup-event is triggered, but the value is not based on the latest element.value but on the old value stored by inputmask, so element. value will not change, and the input-event needs to be triggered in advance to notify inputmask
=> fix: Trigger input-event before keyup-event to prevent inputmask from resetting element.value

src/components/newtab/workflow/edit/EditExecuteWorkflow.vue, src/locales/en/blocks.json, src/locales/it/blocks.json, src/locales/uk/blocks.json, src/locales/vi/blocks.json, src/locales/zh-TW/blocks.json, src/locales/zh/blocks.json, src/utils/shared.js, src/workflowEngine/blocksHandler/handlerExecuteWorkflow.js
=> Feat: Use all current workflow globalData

src/content/showExecutedBlock.js
The  `z-index`  is not working due to a styling error.
=> Fix: showExecutedBlock style error

src/content/blocksHandler/handlerEventClick.js
When my workflow encounters bot detection, I tried using  `debugMode`  to simulate the click event (as I had no issues with simulating clicks in Playwright). However, executing only  `mousePressed`  and  `mouseReleased`  did not solve the problem, as most bot detections are related to mouse movement. So, I added the  `mouseMoved`  command, and now it can successfully bypass bot detection (at least in my scenario, haha).
=> feat: In  `debugMode` , the  `EventClick`  still cannot bypass the bot detection.

src/workflowEngine/templating/mustacheReplacer.js
With the updated regular expression to support  `\"|\'` , it should be able to handle scenarios where both single and double quotes are present. However, it's true that using only a regular expression might not cover all possible edge cases.
Test cases:
1.  `s = "'',''" // ["''", "''"]`
2.  `s = "',',''" // ["','", "''"]`
3.  `s = "'\',',''" // ["'','", "''"]`
=> fix: #1372

src/content/blocksHandler/handlerForms.js
use `Input.dispatchKeyEvent` + **Delete**
> src/content/blocksHandler/handlerForms.js:29
```js
if (data.clearValue) {
const backspaceCommands = new Array(element.value?.length ?? 0).fill({
type: 'keyDown',
unmodifiedText: 'Delete',
text: 'Delete',
windowsVirtualKeyCode: 46,
});
await sendMessage(
'debugger:type',
{ commands: backspaceCommands, tabId: block.activeTabId, delay: 0 },
'background'
);
}
```
=> Fix: in debugger mode clear value

src/workflowEngine/WorkflowEngine.js
in the `settings.debugMode === true`, `workers.delete` need wait detach debugger:
=> Fix:  detach debugger fail

src/workflowEngine/WorkflowEngine.js, src/workflowEngine/blocksHandler/handlerExecuteWorkflow.js
The parent `WorkflowEngine` will override the storage data modified by the child `WorkflowEngine` ($$variable/table).
> I use a random referenceData.workflow.id for data transmission, which may not be the optimal solution.
=> Feat: merge all data from all workflows

src/newtab/pages/workflows/[id].vue
Fix bug #1532 by deselect all selected nodes before leave.
=> Fix: #1532 deleting selected blocks in inactive tab

src/stores/workflow.js
pinnedWorkflowIndex will be 'undefined' if 'pin' never use
=> Fix: error when delete workflow

src/newtab/pages/Workflows.vue, src/popup/pages/Home.vue
1.The wrong id was used when deleting hosted workflows from the popup page.
2.When opening the workflow detail page from other pages like the popup or logs page, the current route path was being replaced by the activeTab stored in localStorage. I changed it to prioritize using the current route path when it is a child route. You may need to evaluate if this change has any unintended side effects. Here is a gif demonstrating the bug:
=> Fix bugs with deleting hosted workflows and opening workflows

src/manifest.chrome.json, src/utils/helper.js
fix: ensure correct active tab detection from the extension dashboard
When trying to detect the **"active tab"** from the **Automa extension's dashboard** (like when triggering a CSS selector), the dashboard window is always focused. This caused the original code to fail in correctly identifying the active tab and throw error.
Now, using the [`windows.getLastFocused()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/getLastFocused) API to query "`normal`" type window, we can accurately fetch the active tab without extension's panel window.
That's fix both of **"Element Selector"** and **"Record Workflow"** / **"Record from here"** functions.
Issue example screenshot:
=> fix: ensure correct active tab detection from the extension dashboard

src/components/newtab/workflow/edit/EditInteractionBase.vue, src/components/ui/UiExpand.vue, src/components/ui/UiTextarea.vue
- Change Block's CSS/XPath Selector to a resizable `textarea` that automatically adjusts to the content height by default, instead of a narrow one-line `input`.
- **Expand block options by default** to clearly show which options are available or have been modified when switching between each blocks.
Preview screenshot:
=> feat: improve blocks configuration UI interaction

src/components/ui/UiAutocomplete.vue
fix the the issue (The bug prevents users from navigating the cursor within a multiline text input field using keyboard arrow keys) 
[!1927](https://github.com/AutomaApp/automa/issues/1927)
=> fix(ui/autocomplete): prevent keydown handling when popover is hidden

src/newtab/pages/workflows/[id].vue
This time, we mainly added the drag and drop function in the sidebar. Currently, we have also modified the CSS selector components of some functional modules. The current CSS selector is a single line input, which is very cumbersome and not intuitive to fill in each time. Currently, I have changed to multi line input. If the boss thinks it is possible, I will request to pull it once. Thank you
=> feat: add sidebar drag and drop functionality
